version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - storage:/var/www/html/storage
        ports:
            - "8000:80"
        depends_on:
            - mysql_db
        environment:
            DB_HOST: mysql_db
            DB_PORT: 3306
            DB_DATABASE: red_juggernaut
            DB_USERNAME: root
            DB_PASSWORD: root

    mysql_db:
        image: mysql:8.0
        ports:
            - "33060:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: red_juggernaut
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
    storage:

