version: '3.8'

services:
    red_juggernaut:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - storage:/var/www/html/storage
        depends_on:
            - mysql
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: red_juggernaut
            DB_USERNAME: root
            DB_PASSWORD: root

    mysql_db:
        image: mysql:8.0
        ports:
            - "33060:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: red_juggernaut
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    storage:
    mysql_data:
